### ISSUE TITLE
Default ctor & default dtor

### ISSUE THREAD

**Issue by Alan5142** [FFahrenheit/DiscShop#1]
Hey!, tres cosas:

Si el ctor esta vacío. puedes declararlo como:
```cpp
Client() = default;
```
https://github.com/FFahrenheit/DiscShop/blob/1d45b40eb65e146d959fc52fc2593e12051a6de1/include/Client.h#L9

https://github.com/FFahrenheit/DiscShop/blob/1d45b40eb65e146d959fc52fc2593e12051a6de1/src/Client.cpp#L6-L8

Si el dtor esta vacío. puedes declararlo como:
```cpp
~Client() = default;
```
https://github.com/FFahrenheit/DiscShop/blob/1d45b40eb65e146d959fc52fc2593e12051a6de1/include/Client.h#L10

https://github.com/FFahrenheit/DiscShop/blob/1d45b40eb65e146d959fc52fc2593e12051a6de1/src/Client.cpp#L10-L12

Si no necesitas polimorfismo, no utilices virtual, así evitas la generación de una vtable

**Comment by FFahrenheit** [comment]
Gracias! Los corregiré por cuestión de performance y estética. La verdad están así porque el IDE los pone por default (CodeBlocks) jaja.
